# Plantilla de Extracción y Limpieza de Datos

### 1. Cargar un archivo desde Google Drive

Primero, montaremos Google Drive para acceder a tus archivos.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

### 2. Configuración de la ruta del archivo

Define aquí la ruta a tu archivo CSV o Excel en Google Drive. Esta variable será usada por las celdas posteriores para cargar los datos.

In [ ]:
# Define aquí la ruta a tu archivo CSV o Excel en Google Drive
# Ejemplo: '/content/drive/MyDrive/Kaggle/nombre_de_tu_archivo.csv'
file_path_global = '/content/drive/MyDrive/Kaggle/Adidas US Sales.csv'

print(f"Ruta del archivo configurada: {file_path_global}")

Ruta del archivo configurada: /content/drive/MyDrive/Kaggle/Adidas US Sales.csv

Ahora, puedes especificar la ruta de tu archivo CSV o Excel. **Asegúrate de reemplazar `'RUTA_A_TU_ARCHIVO.csv'` con la ruta real de tu archivo en Google Drive.**

Por ejemplo, si tu archivo está en `Mi Drive/Carpeta/mi_archivo.csv`, la ruta sería `/content/drive/MyDrive/Carpeta/mi_archivo.csv`.

### 3. Cargar el DataFrame

In [ ]:
import pandas as pd

try:
    # Si es un archivo CSV, usa pd.read_csv
    df = pd.read_csv(file_path_global)
    print("Archivo CSV cargado exitosamente.")
    display(df.head())
except FileNotFoundError:
    print(f"Error: El archivo no se encontró en la ruta especificada: {file_path_global}")
    print("Por favor, verifica la ruta y asegúrate de que Google Drive esté montado correctamente.")
    df = None
except Exception as e:
    print(f"Ocurrió un error al cargar el archivo: {e}")
    df = None

Archivo CSV cargado exitosamente.

,sales_id,retailer,retailer_id,invoice_date,region,state,city,product,price_per_unit,units_sold,total_sales,operating_profit,sales_method
0,1,Foot Locker,1185732,2021-11-06,Southeast,South Carolina,Charleston,Men's Street Footwear,50,278,13900,792,Online
1,2,Foot Locker,1185732,2020-03-14,Northeast,New York,New York,Men's Apparel,46,278,12788,435,Outlet
2,3,West Gear,1128299,2021-01-19,West,California,San Francisco,Men's Athletic Footwear,47,278,13066,287,Outlet
3,4,Walmart,1128299,2021-06-17,Southeast,Florida,Orlando,Women's Apparel,103,218,22454,1257,Online
4,5,Sports Direct,1197831,2021-09-14,South,Alabama,Birmingham,Women's Street Footwear,36,278,10008,530,Outlet

### 4. Revisión inicial del DataFrame

Verifica las dimensiones, los tipos de datos y un resumen estadístico.

In [ ]:
# Continuar solo si el DataFrame se cargó correctamente
if 'df' in locals() and df is not None:
    # Información general
    print(df.shape)
    print("\n")
    display(df.head())
    print("\n")
    display(df.info())
    print("\n")
    display(df.describe(include="all"))
else:
    print("El DataFrame 'df' no está cargado. Por favor, asegúrate de ejecutar la celda de carga de datos.")

(9637, 13)

,sales_id,retailer,retailer_id,invoice_date,region,state,city,product,price_per_unit,units_sold,total_sales,operating_profit,sales_method
0,1,Foot Locker,1185732,2021-11-06,Southeast,South Carolina,Charleston,Men's Street Footwear,50,278,13900,792,Online
1,2,Foot Locker,1185732,2020-03-14,Northeast,New York,New York,Men's Apparel,46,278,12788,435,Outlet
2,3,West Gear,1128299,2021-01-19,West,California,San Francisco,Men's Athletic Footwear,47,278,13066,287,Outlet
3,4,Walmart,1128299,2021-06-17,Southeast,Florida,Orlando,Women's Apparel,103,218,22454,1257,Online
4,5,Sports Direct,1197831,2021-09-14,South,Alabama,Birmingham,Women's Street Footwear,36,278,10008,530,Outlet

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9637 entries, 0 to 9636
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   sales_id          9637 non-null   int64
 1   retailer          9637 non-null   object
 2   retailer_id       9637 non-null   int64
 3   invoice_date      9637 non-null   object
 4   region            9637 non-null   object
 5   state             9637 non-null   object
 6   city              9637 non-null   object
 7   product           9637 non-null   object
 8   price_per_unit    9637 non-null   int64
 9   units_sold        9637 non-null   int64
 10  total_sales       9637 non-null   int64
 11  operating_profit  9637 non-null   int64
 12  sales_method      9637 non-null   object
dtypes: int64(6), object(7)
memory usage: 978.9+ KB

None

,sales_id,retailer,retailer_id,invoice_date,region,state,city,product,price_per_unit,units_sold,total_sales,operating_profit,sales_method
count,9637.000000,9637,9.637000e+03,9637,9637,9637,9637,9637,9637.000000,9637.000000,9637.000000,9637.000000,9637
unique,NaN,6,NaN,724,5,50,52,6,NaN,NaN,NaN,NaN,3
top,NaN,Foot Locker,NaN,2021-01-17,West,Texas,Portland,Men's Street Footwear,NaN,NaN,NaN,NaN,Online
freq,NaN,2630,NaN,77,2446,430,360,1610,NaN,NaN,NaN,NaN,4887
mean,4819.000000,NaN,1.173846e+06,NaN,NaN,NaN,NaN,NaN,45.218948,256.886064,12451.621355,3440.706029,NaN
std,2782.106606,NaN,2.636304e+04,NaN,NaN,NaN,NaN,NaN,14.704520,214.097600,12708.094249,5418.210200,NaN
min,1.000000,NaN,1.128299e+06,NaN,NaN,NaN,NaN,NaN,7.000000,6.000000,160.000000,8.000000,NaN
25%,2410.000000,NaN,1.185732e+06,NaN,NaN,NaN,NaN,NaN,35.000000,106.000000,4068.000000,192.000000,NaN
50%,4819.000000,NaN,1.185732e+06,NaN,NaN,NaN,NaN,NaN,45.000000,176.000000,7805.000000,437.000000,NaN
75%,7228.000000,NaN,1.185732e+06,NaN,NaN,NaN,NaN,NaN,55.000000,350.000000,15834.000000,5200.000000,NaN
max,9637.000000,NaN,1.197831e+06,NaN,NaN,NaN,NaN,NaN,110.000000,1275.000000,82500.000000,39000.000000,NaN

### 5. Limpieza y estandarización de nombres de columnas

Estandarizamos los nombres de las columnas para facilitar el manejo.

In [ ]:
if 'df' in locals() and df is not None:
    # Limpieza profesional de nombres de columnas
    df.columns = (
        df.columns
          .str.strip() # Elimina espacios en blanco al inicio y final
          .str.lower() # Convierte a minúsculas
          .str.replace(" ", "_", regex=False) # Reemplaza espacios con guiones bajos
          .str.replace("/", "_", regex=False) # Reemplaza barras con guiones bajos
          .str.replace("-", "_", regex=False) # Reemplaza guiones con guiones bajos
          .str.replace("__", "_", regex=False) # Reemplaza dobles guiones bajos con uno solo (por si acaso)
    )

    print("Nombres de columnas estandarizados:")
    print(df.columns.tolist())
else:
    print("El DataFrame 'df' no está cargado. Por favor, asegúrate de ejecutar la celda de carga de datos.")

Nombres de columnas estandarizados:
['sales_id', 'retailer', 'retailer_id', 'invoice_date', 'region', 'state', 'city', 'product', 'price_per_unit', 'units_sold', 'total_sales', 'operating_profit', 'sales_method']

### 6. Revisión de valores nulos y duplicados

In [ ]:
if 'df' in locals() and df is not None:
    # Valores nulos
    nulos = df.isnull().sum().sort_values(ascending=False)
    print("Valores nulos por columna:")
    display(nulos[nulos > 0])

    # Duplicados
    print("\nDuplicados:\n", df.duplicated().sum())

    # Tipos de datos
    print("\nTipos de datos:\n")
    display(df.dtypes)
else:
    print("El DataFrame 'df' no está cargado. Por favor, asegúrate de ejecutar la celda de carga de datos.")

Valores nulos por columna:

Series([], dtype: int64)

Duplicados:
 0

Tipos de datos:

sales_id             int64
retailer            object
retailer_id          int64
invoice_date        object
region              object
state               object
city                object
product             object
price_per_unit       int64
units_sold           int64
total_sales          int64
operating_profit     int64
sales_method        object
dtype: object

### 7. Conversión y Validación de Columnas de Fecha

Convertir columnas que representan fechas a un formato `datetime` es crucial para análisis temporales. También validaremos que los identificadores numéricos sean del tipo correcto.

In [ ]:
# Detectar automáticamente posibles columnas de fecha

if 'df' in locals() and df is not None:

    date_columns = []

    for col in df.select_dtypes(include='object').columns:

        # Intentar convertir sin mostrar warnings
        converted = pd.to_datetime(
            df[col],
            errors='coerce',
            format='mixed'
        )

        porcentaje_fecha = converted.notna().mean()

        # Si al menos el 70% puede interpretarse como fecha
        if porcentaje_fecha >= 0.70:
            df[col] = converted
            date_columns.append(col)

    print("Columnas detectadas como fecha:")

    if date_columns:
        for col in date_columns:
            print(f"✓ {col}")
    else:
        print("No se detectaron columnas de fecha.")

Columnas detectadas como fecha:
✓ invoice_date

In [ ]:
# Clasificar automáticamente las columnas del dataset

numeric_columns = df.select_dtypes(include='number').columns.tolist()
categorical_columns = df.select_dtypes(include=['object', 'category']).columns.tolist()
datetime_columns = df.select_dtypes(include=['datetime', 'datetimetz']).columns.tolist()

print("=== CLASIFICACIÓN DE COLUMNAS ===")

print("\nNuméricas:")
print(numeric_columns if numeric_columns else "Ninguna")

print("\nCategóricas / texto:")
print(categorical_columns if categorical_columns else "Ninguna")

print("\nFechas:")
print(datetime_columns if datetime_columns else "Ninguna")

=== CLASIFICACIÓN DE COLUMNAS ===

Numéricas:
['sales_id', 'retailer_id', 'price_per_unit', 'units_sold', 'total_sales', 'operating_profit']

Categóricas / texto:
['retailer', 'region', 'state', 'city', 'product', 'sales_method']

Fechas:
['invoice_date']

### 8. Estandarización de Datos Categóricos

Aseguramos que los valores en columnas categóricas sean consistentes, por ejemplo, convirtiendo a minúsculas o reemplazando variantes.

In [ ]:
# Estandarización automática de variables categóricas

for col in df.select_dtypes(include=['object', 'category']).columns:

    df[col] = (
        df[col]
        .astype(str)
        .str.strip()
        .str.lower()
    )

print("=== VARIABLES CATEGÓRICAS ESTANDARIZADAS ===")

categorical_cols = df.select_dtypes(
    include=['object', 'category']
).columns.tolist()

print(categorical_cols if categorical_cols else "No se detectaron variables categóricas.")

=== VARIABLES CATEGÓRICAS ESTANDARIZADAS ===
['retailer', 'region', 'state', 'city', 'product', 'sales_method']

### 9. Análisis Exploratorio de Datos (EDA)
Exploramos los datos mediante estadísticas y visualizaciones para identificar tendencias, distribuciones, anomalías y patrones relevantes.

In [ ]:
# Perfil automático de calidad de datos

quality_report = pd.DataFrame({
    'columna': df.columns,
    'tipo': df.dtypes.astype(str).values,
    'nulos': df.isnull().sum().values,
    'nulos_%': (df.isnull().mean() * 100).round(2).values,
    'unicos': df.nunique(dropna=False).values
})

quality_report['duplicados_dataset'] = df.duplicated().sum()

print("=== REPORTE DE CALIDAD ===")
display(quality_report)

print("\nFilas duplicadas:", df.duplicated().sum())
print("Total de filas:", len(df))
print("Total de columnas:", len(df.columns))

=== REPORTE DE CALIDAD ===

,columna,tipo,nulos,nulos_%,unicos,duplicados_dataset
0,sales_id,int64,0,0.0,9637,0
1,retailer,object,0,0.0,6,0
2,retailer_id,int64,0,0.0,4,0
3,invoice_date,datetime64[ns],0,0.0,724,0
4,region,object,0,0.0,5,0
5,state,object,0,0.0,50,0
6,city,object,0,0.0,52,0
7,product,object,0,0.0,6,0
8,price_per_unit,int64,0,0.0,94,0
9,units_sold,int64,0,0.0,360,0
10,total_sales,int64,0,0.0,3081,0
11,operating_profit,int64,0,0.0,1529,0
12,sales_method,object,0,0.0,3,0

Filas duplicadas: 0
Total de filas: 9637
Total de columnas: 13

In [ ]:
# Detectar automáticamente el rol probable de cada columna

column_roles = []

for col in df.columns:

    unique_ratio = df[col].nunique(dropna=False) / len(df)
    col_lower = col.lower()

    # Fecha
    if pd.api.types.is_datetime64_any_dtype(df[col]):
        role = "fecha"

    # Posible ID: alta unicidad + nombre compatible con identificador
    elif (
        unique_ratio >= 0.95
        and any(x in col_lower for x in ['id', 'code', 'codigo', 'case_no', 'number', 'numero'])
    ):
        role = "posible_id"

    # Numéricas
    elif pd.api.types.is_numeric_dtype(df[col]):

        if df[col].nunique() <= 10:
            role = "numerica_discreta"
        else:
            role = "numerica_continua"

    # Texto / categorías
    else:

        if df[col].nunique() <= 20:
            role = "categorica"
        else:
            role = "texto_alta_cardinalidad"

    column_roles.append({
        "columna": col,
        "rol_probable": role,
        "valores_unicos": df[col].nunique(),
        "ratio_unicidad": round(unique_ratio, 3)
    })

roles_report = pd.DataFrame(column_roles)

print("=== ROLES PROBABLES DE LAS COLUMNAS ===")
display(roles_report)

=== ROLES PROBABLES DE LAS COLUMNAS ===

             columna             rol_probable  valores_unicos  ratio_unicidad
0           sales_id               posible_id            9637           1.000
1           retailer               categorica               6           0.001
2        retailer_id        numerica_discreta               4           0.000
3       invoice_date                    fecha             724           0.075
4             region               categorica               5           0.001
5              state  texto_alta_cardinalidad              50           0.005
6               city  texto_alta_cardinalidad              52           0.005
7            product               categorica               6           0.001
8     price_per_unit        numerica_continua              94           0.010
9         units_sold        numerica_continua             360           0.037
10       total_sales        numerica_continua            3081           0.320
11  operating_profit        numerica_continua            1529           0.159
12      sales_method               categorica               3           0.000

### 10. Potencial Analítico
Evaluamos qué variables ofrecen mejores posibilidades para realizar métricas, segmentaciones, comparaciones y análisis temporales.

In [ ]:
# Seleccionar automáticamente variables útiles para análisis

ids = roles_report.loc[
    roles_report['rol_probable'] == 'posible_id',
    'columna'
].tolist()

fechas = roles_report.loc[
    roles_report['rol_probable'] == 'fecha',
    'columna'
].tolist()

categoricas = roles_report.loc[
    roles_report['rol_probable'] == 'categorica',
    'columna'
].tolist()

numericas = roles_report.loc[
    roles_report['rol_probable'].isin(
        ['numerica_continua', 'numerica_discreta']
    ),
    'columna'
].tolist()

print("=== VARIABLES DISPONIBLES PARA ANÁLISIS ===")

print("\nIDs (se excluyen del análisis):")
print(ids if ids else "Ninguno")

print("\nFechas:")
print(fechas if fechas else "Ninguna")

print("\nCategóricas:")
print(categoricas if categoricas else "Ninguna")

print("\nNuméricas:")
print(numericas if numericas else "Ninguna")

=== VARIABLES DISPONIBLES PARA ANÁLISIS ===

IDs (se excluyen del análisis):
['sales_id']

Fechas:
['invoice_date']

Categóricas:
['retailer', 'region', 'product', 'sales_method']

Numéricas:
['retailer_id', 'price_per_unit', 'units_sold', 'total_sales', 'operating_profit']

In [ ]:
# Evaluar potencial analítico de las variables

analysis_candidates = []

for col in df.columns:

    role = roles_report.loc[
        roles_report['columna'] == col,
        'rol_probable'
    ].values[0]

    score = 0
    motivos = []

    if role == "fecha":
        score += 2
        motivos.append("permite análisis temporal")

    elif role == "categorica":
        unique_count = df[col].nunique()

        if 2 <= unique_count <= 15:
            score += 3
            motivos.append("buena segmentación")

        elif unique_count <= 30:
            score += 2
            motivos.append("segmentación posible")

    elif role in ["numerica_continua", "numerica_discreta"]:
        score += 3
        motivos.append("permite métricas y comparaciones")

        if df[col].std() > 0:
            score += 1
            motivos.append("presenta variabilidad")

    elif role == "posible_id":
        motivos.append("identificador; baja utilidad analítica directa")

    analysis_candidates.append({
        "columna": col,
        "rol": role,
        "score_analitico": score,
        "motivos": ", ".join(motivos)
    })

potential_report = pd.DataFrame(analysis_candidates)

potential_report = potential_report.sort_values(
    by="score_analitico",
    ascending=False
)

print("=== POTENCIAL ANALÍTICO DE LAS VARIABLES ===")
display(potential_report)

=== POTENCIAL ANALÍTICO DE LAS VARIABLES ===

,columna,rol,score_analitico,motivos
2,retailer_id,numerica_discreta,4,"permite métricas y comparaciones, presenta var..."
9,units_sold,numerica_continua,4,"permite métricas y comparaciones, presenta var..."
10,total_sales,numerica_continua,4,"permite métricas y comparaciones, presenta var..."
11,operating_profit,numerica_continua,4,"permite métricas y comparaciones, presenta var..."
8,price_per_unit,numerica_continua,4,"permite métricas y comparaciones, presenta var..."
7,product,categorica,3,buena segmentación
12,sales_method,categorica,3,buena segmentación
1,retailer,categorica,3,buena segmentación
4,region,categorica,3,buena segmentación
3,invoice_date,fecha,2,permite análisis temporal
0,sales_id,posible_id,0,identificador; baja utilidad analítica directa
5,state,texto_alta_cardinalidad,0,
6,city,texto_alta_cardinalidad,0,

### 11. Relaciones Prometedoras
Buscamos asociaciones entre variables numéricas, categóricas y temporales que puedan revelar patrones relevantes.

In [ ]:
# Buscar relaciones prometedoras con medidas comparables

promising_relations = []

# 1. Numérica vs categórica: Eta cuadrado
for num_col in numericas:
    for cat_col in categoricas:

        if 2 <= df[cat_col].nunique() <= 15:

            temp = df[[num_col, cat_col]].dropna()

            if len(temp) > 1:

                media_general = temp[num_col].mean()

                ss_total = ((temp[num_col] - media_general) ** 2).sum()

                ss_between = sum(
                    len(grupo) * (grupo[num_col].mean() - media_general) ** 2
                    for _, grupo in temp.groupby(cat_col)
                )

                if ss_total > 0:
                    eta2 = ss_between / ss_total

                    if eta2 >= 0.05:
                        promising_relations.append({
                            "tipo": "numerica_vs_categorica",
                            "variable_1": num_col,
                            "variable_2": cat_col,
                            "fuerza": round(eta2, 3),
                            "motivo": "diferencias relevantes entre categorías"
                        })

# 2. Numérica vs numérica: correlación
for i in range(len(numericas)):
    for j in range(i + 1, len(numericas)):

        col1 = numericas[i]
        col2 = numericas[j]

        corr = df[[col1, col2]].corr().iloc[0, 1]

        if pd.notna(corr) and abs(corr) >= 0.30:
            promising_relations.append({
                "tipo": "numerica_vs_numerica",
                "variable_1": col1,
                "variable_2": col2,
                "fuerza": round(abs(corr), 3),
                "motivo": f"correlación {round(corr, 2)}"
            })

relations_report = pd.DataFrame(promising_relations)

print("=== RELACIONES PROMETEDORAS ===")

if relations_report.empty:
    print("No se detectaron relaciones destacables.")
else:
    relations_report = relations_report.sort_values(
        by="fuerza",
        ascending=False
    )

    display(relations_report.head(20))

=== RELACIONES PROMETEDORAS ===

,tipo,variable_1,variable_2,fuerza,motivo
13,numerica_vs_numerica,total_sales,operating_profit,0.929,correlación 0.93
11,numerica_vs_numerica,units_sold,total_sales,0.919,correlación 0.92
12,numerica_vs_numerica,units_sold,operating_profit,0.893,correlación 0.89
9,numerica_vs_numerica,price_per_unit,total_sales,0.539,correlación 0.54
1,numerica_vs_categorica,retailer_id,region,0.396,diferencias relevantes entre categorías
10,numerica_vs_numerica,price_per_unit,operating_profit,0.394,correlación 0.39
8,numerica_vs_numerica,retailer_id,price_per_unit,0.391,correlación -0.39
7,numerica_vs_categorica,operating_profit,sales_method,0.130,diferencias relevantes entre categorías
5,numerica_vs_categorica,units_sold,sales_method,0.127,diferencias relevantes entre categorías
0,numerica_vs_categorica,retailer_id,retailer,0.122,diferencias relevantes entre categorías
6,numerica_vs_categorica,total_sales,sales_method,0.106,diferencias relevantes entre categorías
2,numerica_vs_categorica,price_per_unit,region,0.104,diferencias relevantes entre categorías
3,numerica_vs_categorica,price_per_unit,product,0.085,diferencias relevantes entre categorías
4,numerica_vs_categorica,units_sold,product,0.076,diferencias relevantes entre categorías

### 12. Candidatos de Hallazgos
Transformamos los patrones detectados en posibles hallazgos que luego deberán ser validados con evidencia.

In [ ]:
# Generar candidatos de hallazgo en lenguaje natural

hallazgos = []

for _, row in relations_report.iterrows():

    tipo = row["tipo"]
    var1 = row["variable_1"]
    var2 = row["variable_2"]
    fuerza = row["fuerza"]

    if tipo == "numerica_vs_categorica":

        if fuerza >= 0.50:
            nivel = "muy marcada"
        elif fuerza >= 0.20:
            nivel = "moderada"
        else:
            nivel = "leve"

        texto = (
            f"La variable '{var1}' presenta una diferencia {nivel} "
            f"según las categorías de '{var2}' "
            f"(fuerza = {fuerza})."
        )

    elif tipo == "numerica_vs_numerica":

        if fuerza >= 0.70:
            nivel = "fuerte"
        elif fuerza >= 0.50:
            nivel = "moderada"
        else:
            nivel = "débil"

        texto = (
            f"Existe una relación {nivel} entre '{var1}' y '{var2}' "
            f"(fuerza = {fuerza})."
        )

    hallazgos.append({
        "variable_1": var1,
        "variable_2": var2,
        "fuerza": fuerza,
        "candidato_hallazgo": texto
    })

hallazgos_report = pd.DataFrame(hallazgos)

print("=== CANDIDATOS DE HALLAZGO ===")

if hallazgos_report.empty:
    print("No se generaron candidatos de hallazgo.")
else:
    display(hallazgos_report)

=== CANDIDATOS DE HALLAZGO ===

,variable_1,variable_2,fuerza,candidato_hallazgo
0,total_sales,operating_profit,0.929,Existe una relación fuerte entre 'total_sales'...
1,units_sold,total_sales,0.919,Existe una relación fuerte entre 'units_sold' ...
2,units_sold,operating_profit,0.893,Existe una relación fuerte entre 'units_sold' ...
3,price_per_unit,total_sales,0.539,Existe una relación moderada entre 'price_per_...
4,retailer_id,region,0.396,La variable 'retailer_id' presenta una diferen...
5,price_per_unit,operating_profit,0.394,Existe una relación débil entre 'price_per_uni...
6,retailer_id,price_per_unit,0.391,Existe una relación débil entre 'retailer_id' ...
7,operating_profit,sales_method,0.130,La variable 'operating_profit' presenta una di...
8,units_sold,sales_method,0.127,La variable 'units_sold' presenta una diferenc...
9,retailer_id,retailer,0.122,La variable 'retailer_id' presenta una diferen...
10,total_sales,sales_method,0.106,La variable 'total_sales' presenta una diferen...
11,price_per_unit,region,0.104,La variable 'price_per_unit' presenta una dife...
12,price_per_unit,product,0.085,La variable 'price_per_unit' presenta una dife...
13,units_sold,product,0.076,La variable 'units_sold' presenta una diferenc...

### 13. Evidencia de Hallazgos
Validamos cada posible hallazgo mediante métricas, comparaciones y visualizaciones obtenidas directamente del dataset.

In [ ]:
# Generar evidencia automática para los candidatos de hallazgo

evidencias = []

for _, row in relations_report.iterrows():

    tipo = row["tipo"]
    var1 = row["variable_1"]
    var2 = row["variable_2"]
    fuerza = row["fuerza"]

    if tipo == "numerica_vs_categorica":

        resumen = (
            df.groupby(var2)[var1]
            .agg(["count", "mean", "median"])
            .round(2)
            .reset_index()
            .sort_values("mean", ascending=False)
        )

        top = resumen.iloc[0]
        bottom = resumen.iloc[-1]

        evidencias.append({
            "variable_1": var1,
            "variable_2": var2,
            "fuerza": fuerza,
            "evidencia": (
                f"Mayor promedio: {top[var2]} = {top['mean']}. "
                f"Menor promedio: {bottom[var2]} = {bottom['mean']}. "
                f"Diferencia = {round(top['mean'] - bottom['mean'], 2)}."
            )
        })

    elif tipo == "numerica_vs_numerica":

        corr = df[[var1, var2]].corr().iloc[0, 1]

        evidencias.append({
            "variable_1": var1,
            "variable_2": var2,
            "fuerza": fuerza,
            "evidencia": (
                f"Correlación = {round(corr, 2)}. "
                f"A mayor '{var1}', {'tiende a aumentar' if corr > 0 else 'tiende a disminuir'} '{var2}'."
            )
        })

evidence_report = pd.DataFrame(evidencias)

print("=== EVIDENCIA DE LOS CANDIDATOS ===")

if evidence_report.empty:
    print("No se generó evidencia.")
else:
    display(evidence_report)

=== EVIDENCIA DE LOS CANDIDATOS ===

,variable_1,variable_2,fuerza,evidencia
0,total_sales,operating_profit,0.929,"Correlación = 0.93. A mayor 'total_sales', tie..."
1,units_sold,total_sales,0.919,"Correlación = 0.92. A mayor 'units_sold', tien..."
2,units_sold,operating_profit,0.893,"Correlación = 0.89. A mayor 'units_sold', tien..."
3,price_per_unit,total_sales,0.539,"Correlación = 0.54. A mayor 'price_per_unit', ..."
4,retailer_id,region,0.396,Mayor promedio: south = 1188156.49. Menor prom...
5,price_per_unit,operating_profit,0.394,"Correlación = 0.39. A mayor 'price_per_unit', ..."
6,retailer_id,price_per_unit,0.391,"Correlación = -0.39. A mayor 'retailer_id', ti..."
7,operating_profit,sales_method,0.130,Mayor promedio: in-store = 7332.92. Menor prom...
8,units_sold,sales_method,0.127,Mayor promedio: in-store = 396.55. Menor prome...
9,retailer_id,retailer,0.122,Mayor promedio: amazon = 1185732.0. Menor prom...
10,total_sales,sales_method,0.106,Mayor promedio: in-store = 20496.77. Menor pro...
11,price_per_unit,region,0.104,Mayor promedio: southeast = 50.18. Menor prome...
12,price_per_unit,product,0.085,Mayor promedio: women's apparel = 51.58. Menor...
13,units_sold,product,0.076,Mayor promedio: men's street footwear = 368.52...

### 14. Ranking de Hallazgos
Priorizamos los hallazgos según la fuerza de la evidencia, su relevancia y su posible impacto para el análisis.

In [ ]:
## Puntuar candidatos de hallazgo

scored_findings = []

# Variable objetivo opcional
# Usar None si no existe una variable objetivo clara
target_variable = None

for _, row in evidence_report.iterrows():

    fuerza = row["fuerza"]
    var1 = row["variable_1"]
    var2 = row["variable_2"]
    evidencia = row["evidencia"]

    # --------------------------------------------------
    # 0. Excluir variables redundantes / equivalentes
    # --------------------------------------------------

    v1 = var1.lower()
    v2 = var2.lower()

    # Ejemplos:
    # education <-> education_label
    # jobsatisfaction <-> jobsatisfaction_label
    # performancerating <-> performancerating_label

    redundante = (
        v2 == f"{v1}_label"
        or v1 == f"{v2}_label"
        or v2 == f"{v1}_name"
        or v1 == f"{v2}_name"
        or v2 == f"{v1}_desc"
        or v1 == f"{v2}_desc"
    )

    if redundante:
        continue

    score = 0
    relevancia_objetivo = 0

    # --------------------------------------------------
    # 1. Fuerza estadística
    # --------------------------------------------------

    if fuerza >= 0.70:
        score += 3
    elif fuerza >= 0.40:
        score += 2
    elif fuerza >= 0.10:
        score += 1

    # --------------------------------------------------
    # 2. Variables útiles
    # --------------------------------------------------

    if var1 in numericas:
        score += 1

    if var2 in categoricas or var2 in numericas:
        score += 1

    # --------------------------------------------------
    # 3. Relevancia respecto de variable objetivo
    # --------------------------------------------------

    if (
        target_variable is not None
        and target_variable in [var1, var2]
    ):
        relevancia_objetivo = 3
        score += relevancia_objetivo

    # --------------------------------------------------
    # 4. Clasificación final
    # --------------------------------------------------

    if score >= 6:
        nivel = "Hallazgo fuerte"
    elif score >= 4:
        nivel = "Hallazgo medio"
    else:
        nivel = "Exploratorio"

    scored_findings.append({
        "variable_1": var1,
        "variable_2": var2,
        "fuerza": fuerza,
        "relevancia_objetivo": relevancia_objetivo,
        "score": score,
        "nivel": nivel,
        "evidencia": evidencia
    })


findings_score_report = pd.DataFrame(scored_findings)

if not findings_score_report.empty:
    findings_score_report = findings_score_report.sort_values(
        by=["score", "fuerza"],
        ascending=False
    )

print("=== RANKING DE HALLAZGOS ===")

if findings_score_report.empty:
    print("No se encontraron hallazgos.")
else:
    display(findings_score_report)

=== RANKING DE HALLAZGOS ===

,variable_1,variable_2,fuerza,relevancia_objetivo,score,nivel,evidencia
0,total_sales,operating_profit,0.929,0,5,Hallazgo medio,"Correlación = 0.93. A mayor 'total_sales', tie..."
1,units_sold,total_sales,0.919,0,5,Hallazgo medio,"Correlación = 0.92. A mayor 'units_sold', tien..."
2,units_sold,operating_profit,0.893,0,5,Hallazgo medio,"Correlación = 0.89. A mayor 'units_sold', tien..."
3,price_per_unit,total_sales,0.539,0,4,Hallazgo medio,"Correlación = 0.54. A mayor 'price_per_unit', ..."
4,retailer_id,region,0.396,0,3,Exploratorio,Mayor promedio: south = 1188156.49. Menor prom...
5,price_per_unit,operating_profit,0.394,0,3,Exploratorio,"Correlación = 0.39. A mayor 'price_per_unit', ..."
6,retailer_id,price_per_unit,0.391,0,3,Exploratorio,"Correlación = -0.39. A mayor 'retailer_id', ti..."
7,operating_profit,sales_method,0.130,0,3,Exploratorio,Mayor promedio: in-store = 7332.92. Menor prom...
8,units_sold,sales_method,0.127,0,3,Exploratorio,Mayor promedio: in-store = 396.55. Menor prome...
9,retailer_id,retailer,0.122,0,3,Exploratorio,Mayor promedio: amazon = 1185732.0. Menor prom...
10,total_sales,sales_method,0.106,0,3,Exploratorio,Mayor promedio: in-store = 20496.77. Menor pro...
11,price_per_unit,region,0.104,0,3,Exploratorio,Mayor promedio: southeast = 50.18. Menor prome...
12,price_per_unit,product,0.085,0,2,Exploratorio,Mayor promedio: women's apparel = 51.58. Menor...
13,units_sold,product,0.076,0,2,Exploratorio,Mayor promedio: men's street footwear = 368.52...

### 15. Desarrollo del Proceso ETL
Extraemos, transformamos y organizamos los datos para construir una estructura adecuada para el análisis y la visualización.

### 16. Visualización de Datos y Storytelling
Diseñamos visualizaciones que comuniquen los principales hallazgos y construimos una narrativa clara que explique qué ocurrió y por qué es importante.

### 17. Portfolio Score
Evaluamos el proyecto según la calidad de los datos, profundidad del análisis, relevancia de los hallazgos, calidad visual y valor como caso de portfolio.

In [ ]:
# Evaluar aptitud del dataset para un caso BI / portfolio

score = 0
criterios = []

# Tamaño
if len(df) >= 5000:
    score += 2
    criterios.append("Buen volumen de registros")
elif len(df) >= 500:
    score += 1
    criterios.append("Volumen aceptable")
else:
    criterios.append("Dataset pequeño")

# Variedad de columnas
if len(df.columns) >= 10:
    score += 1
    criterios.append("Buena variedad de variables")

# Variables numéricas
if len(numericas) >= 2:
    score += 2
    criterios.append("Tiene métricas suficientes")

# Variables categóricas
if len(categoricas) >= 2:
    score += 2
    criterios.append("Permite segmentación")

# Fechas
if len(fechas) >= 1:
    score += 1
    criterios.append("Permite análisis temporal")

# Relaciones prometedoras
hallazgos_fuertes = len(
    findings_score_report[
        findings_score_report["nivel"] == "Hallazgo fuerte"
    ]
)

hallazgos_medios = len(
    findings_score_report[
        findings_score_report["nivel"] == "Hallazgo medio"
    ]
)

if hallazgos_fuertes >= 2:
    score += 2
    criterios.append("Tiene varios hallazgos fuertes")
elif hallazgos_fuertes >= 1 or hallazgos_medios >= 2:
    score += 1
    criterios.append("Tiene potencial analítico")

# Clasificación final
if score >= 8:
    resultado = "MUY APTO PARA PORTFOLIO"
elif score >= 6:
    resultado = "APTO PARA PORTFOLIO"
elif score >= 4:
    resultado = "APTITUD MEDIA - REVISAR"
else:
    resultado = "POCO APTO PARA PORTFOLIO"

print("=== PORTFOLIO SCORE ===")
print(f"\nScore: {score}/10")
print(f"Resultado: {resultado}")

print("\nCriterios:")
for criterio in criterios:
    print("•", criterio)

=== PORTFOLIO SCORE ===

Score: 9/10
Resultado: MUY APTO PARA PORTFOLIO

Criterios:
• Buen volumen de registros
• Buena variedad de variables
• Tiene métricas suficientes
• Permite segmentación
• Permite análisis temporal
• Tiene potencial analítico